version: 2.1
jobs:
  test:
    working_directory: ~/atomate
    docker:
      - image: continuumio/miniconda3
      - image: circleci/mongo
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "setup.py" }}
      - run:
          name: Install dependencies
          command: |
            export PATH=$HOME/miniconda3/bin:$PATH
            conda create --name test_env python=3.8
            source activate test_env
            conda install -c conda-forge openbabel gcc_linux-64
            pip install .[complete]
          no_output_timeout: 1h
      - run:
          name: pytest
          command: |
            source activate test_env
            pytest --ignore=atomate/qchem/test_files --cov=atomate --cov-report html:coverage_reports atomate
          no_output_timeout: 1h
      - store_artifacts:
          path: coverage_reports/
          destination: tr1
      - store_test_results:
          path: coverage_reports/

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
